### ISSUE TITLE
Support Folders, Organization Folders and Multibranch Pipelines

### ISSUE THREAD

**Issue by pat2man** [openshift/jenkins-sync-plugin#103]
Managing a large number of builds in Jenkins can get complicated. Folders, Organization Folders and Multibranch plugins can help a lot here. The current setup assumes a job at the root level.

My ideal Github setup:

Organization -> MultiPart Pipeline -> Job <-> OpenShift BuildConfig

This allows a single Jenkins instance for things like PRs are not part of OpenShift and also sync up master branch builds with OpenShift.

**Comment by jimmidyson** [comment]
Great idea. Plus once we support multiple projects (#63) we can use folders to separate namespaced jobs out, including scoping secrets to folders. That would allow us to get close to multi tenancy probably in conjunction with the openshift login plugin.

**Comment by rawlingsj** [comment]
@bparees @gabemontero are there any planned work on this?  

We're looking to use the https://wiki.jenkins-ci.org/display/JENKINS/GitHub+Organization+Folder+Plugin to scan a github org and automatically create jenkins jobs based on a selection or filter.  These jobs would then sync back to openshift creating the related BuildConfigs.

**Comment by bparees** [comment]
not currently planned, no (but the fact that it's not closed means we'd certainly consider doing it at some point).

one thing to keep in mind when we start talking about syncing from jenkins -> openshift is that with https://github.com/openshift/jenkins-sync-plugin/pull/115 the sync plugin will sync *from* multiple namespaces, so when syncing *to* openshift you're going to have to decide what namespace you're going to sync into.

**Comment by jstrachan** [comment]
I wonder if OOTB we sync'd Jenkins pipeline jobs in no folders into the current namespace (the same one that Jenkins runs inside) then for any pipeline jobs in a folder, we only sync'd them if jenkins could see the namespace/project of the same name?

**Comment by jstrachan** [comment]
actually maybe only sync pipeline jobs in folders where the folder name matches a namespace/project? then you can't have 2 matching pipeline jobs (in no folder or in a folder) clashing?

**Comment by rawlingsj** [comment]
Yeah that might be a nice approach.  

As it stands the jenkins job name is namespaced (using a / as the seperator) when a job is created by the sync plugin.  So perhaps instead it could create a folder using the namespace name and it can then work vice versa as above?

**Comment by gabemontero** [comment]
Per discussion with @bparees I've created https://trello.com/c/ucGKOKnt/1158-pipeline-integration-support-folders-organization-folders-and-multibranch-pipelines to track this requirement.

Per our process closing this issue out.  There is a link to his issue in the trello card, so if you want to continue discussions here we shouldn't lose sight of it, but we encourage everyone to switch to the card for discussion.
