### ISSUE TITLE
Move to polling trigger from watches

### ISSUE THREAD

**Issue by jimmidyson** [openshift/jenkins-sync-plugin#105]
Currently the plugin uses watches to check for additions/changes to BuildConfigs & Builds. This uses 3 watches (BuildConfigs, new Builds, cancelled Build requests). A single Build watcher is responsible for triggering Jenkins builds as required. Watches provide very responsive behaviour: as soon as an event happens the sync plugin reacts accordingly. Each watch requires 1 long lived connection. Once multiple namespaces are supported (#63), this will mean 3 connections per namespace. This could exhaust connections to the API server (default max is currently 400 iirc) & therefore adversely impact on other applications & even the cluster state as a whole.

Another approach is to use a polling trigger on each job, equivalent to the default Jenkins SCM polling model: each job would be responsible for polling API server for Builds to run. While this would increase the number of requests to the API server but this should be more scalable as they will be short lived & will therefore not potentially exhaust connections to the API server. Polling can use a shared request queue so that requests can be throttled & polling interval can be configured globally as well as per job. This would of course reduce responsiveness of Build requests to a maximum of polling interval, but I think that is acceptable.

I have a prototype for this which works great & simplifies a number of things, but looking for feedback on the approach from others who know more than me - @bparees @gabemontero @jim-minter ?

**Comment by jim-minter** [comment]
My comments FWIW would be:
a) the build watch and cancelled build watch are arguably needless duplication today - both watch calls resolve to identical API calls on the backend server and are receiving the same information, so it should be possible to use one watch for both things.  That gets you from 3->2.
b) I think what's being done here sounds like it should be a good use case for watches, and moving to polling risks event loss (detect multiple changes per window). If watches don't work with the sync plugin architecture, so be it.  However, if they do and this is actually a case of concerns around future scalability, I'd bring in the relevant openshift architects to discuss.  Oughtn't idle watchers per namespace to be less expensive than recurrent polling per job - TLS setup / query / teardown, per job, etc?

I spotted https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/apiserver-watch.md on my travels and would be interested in knowing if it's done or happening - it would be pretty relevant to this.  Also in master.go:

```
	// TODO: MaxRequestsInFlight should be subdivided by intent, type of behavior, and speed of
	// execution - updates vs reads, long reads vs short reads, fat reads vs skinny reads.
```

**Comment by jimmidyson** [comment]
> the build watch and cancelled build watch are arguably needless duplication today - both watch calls resolve to identical API calls on the backend server and are receiving the same information, so it should be possible to use one watch for both things. That gets you from 3->2.

That is a very good point. There must have been a reason I originally did that, but can't think of what it was now...

> moving to polling risks event loss (detect multiple changes per window)

Arguably this is more likely with a watch architecture, with resyncing required periodically (this currently isn't implemented).

>  Oughtn't idle watchers per namespace to be less expensive than recurrent polling per job - TLS setup / query / teardown, per job, etc?

Connections are pooled & reused & a single connection pool is used per Jenkins so reduces that concern.

> I'd bring in the relevant openshift architects to discuss.

@liggitt @smarterclayton Would love to have your insight on this - it's a fundamental design decision for a lot of components I guess.

**Comment by liggitt** [comment]
definitely collapse the two build watches into one

ideally, you could avoid maintaining local watch state and just re-establish watches with no starting resourceVersion (watch from "now"). You'd miss intermediate events, but if the jenkins plugin is level-driven, that wouldn't matter

long running requests (like watches) are not included in the 400-max-in-flight limit

**Comment by jimmidyson** [comment]
Thanks @liggitt. What do you mean by "level-driven"?

**Comment by bparees** [comment]
@jimmidyson 

level-driven: detect that previously the system state was foo and now it's bar, and since we last ran when it was foo, we need to run.

event-driven: the system sends us an event saying "foo changed to bar" and we run as a result of that event.

**Comment by jimmidyson** [comment]
Thanks.

**Comment by gabemontero** [comment]
A bit of an update / house cleaning:

- there are no longer separate watches for build create/update and build cancel ... see https://github.com/openshift/jenkins-sync-plugin/blob/master/src/main/java/io/fabric8/jenkins/openshiftsync/BuildWatcher.java#L82 and https://github.com/openshift/jenkins-sync-plugin/blob/master/src/main/java/io/fabric8/jenkins/openshiftsync/BuildWatcher.java#L211-L212

- we have 2 PRs in flight that are adding *more* watches, not less .... config maps, image streams, secrets

- possibly more stuff coming with various endeavors on both the fabric side and openshift side

So the ship has sailed on this item IMO :-)

Closing this one out.
