### ISSUE TITLE
Test out ItemListener.onLoaded for startup notification

### ISSUE THREAD

**Issue by jimmidyson** [openshift/jenkins-sync-plugin#109]
As suggested by @scoheb in https://github.com/jenkinsci/openshift-sync-plugin/pull/25#discussion_r88288491:

> I am wondering why you need to do this here? Can you not wait until all jobs are loaded? Take a look at this: http://javadoc.jenkins.io/hudson/model/listeners/ItemListener.html#onLoaded()

**Comment by gabemontero** [comment]
addressed with commit 81262daa263f9c6944468fe2ab20cfe04b065f38 from @scoheb
