### ISSUE TITLE
Switch to PeriodicWork or ASyncPeriodicWork for watcher tasks

### ISSUE THREAD

**Issue by jimmidyson** [openshift/jenkins-sync-plugin#111]
As @scoheb suggests in https://github.com/jenkinsci/openshift-sync-plugin/pull/29#discussion_r89627240

**Comment by gabemontero** [comment]
As we will soon have a `BaseWatcher` that all our watches now extend, extending `PeriodicWork` or `ASyncPeriodicWork` is a bit more cumbersome than when this suggestion first came down.

Converting `BaseWatcher` to an interface with default methods, and then extending one of those two classes, could be the next logical step, but we actually do some extension/overrides of the `BaseWatcher` methods in the classes that extend them.

Going to punt on this one.
