### ISSUE TITLE
Suspected spurious BuildConfig update in PipelineJobListener.java

### ISSUE THREAD

**Issue by jim-minter** [openshift/jenkins-sync-plugin#133]
I think https://github.com/openshift/origin/issues/13694 is caused by PipelineJobListener firing in response to a pipeline being created initially, sending a needless buildconfig update back to OpenShift.  Need to ensure that object updates are not sent back out to OpenShift when they are made in response to an incoming update.

**Comment by jim-minter** [comment]
@gabemontero

**Comment by gabemontero** [comment]
version 0.1.14 of the sync plugin is cooking up in jenkinsci
