### ISSUE TITLE
when using the github org plugin (for CI / CD) deleting a BuildConfig/Job can lead to the BuildConfig/Job coming back again later

### ISSUE THREAD

**Issue by jstrachan** [openshift/jenkins-sync-plugin#141]
when using the openshift.io wizard to create an app we use the github org plugin so that we get the PR  CI / CD builds for projects; which is awesome!
https://www.youtube.com/watch?v=6bGOvF8K4Rg

The downside is that the project name gets added to the `Repository name pattern` in the github org job. Then next time the github org Job runs, it re-generates the BuildConfig/Job again! So the projects come back again!

So we need the jenkins-sync-plugin to detect builds being deleted and remove their repository name pattern if it can be found from the github org job configuration to avoid them coming back again

**Comment by jstrachan** [comment]
lemme try create a PR for this...

**Comment by bparees** [comment]
I'm not fully following the interaction flow here (probably because i don't know how the github org plugin works).

it sounds like you're saying that you do an import using the github org plugin.  This creates some jobs in jenkins (is there a corresponding buildconfig in openshift at this point?  when/how was it created if so?).

Then you delete the buildconfig in openshift(?) and the sync plugin deletes the job in jenkins, but then the github org plugin automatically recreates it because it still thinks it's supposed to be importing it(?)

**Comment by bparees** [comment]
(I want to understand this better because I don't like the idea that the sync plugin needs to go notify random other plugins about things its doing to ensure the system stays consistent).

**Comment by jstrachan** [comment]
so yes when we create a new project in OSIO we:

* create a github org job once (per github org) which deals with PRs / branches / CI jobs and lets folks import other repos etc
* create a BC which syncs to a jenkins job (or folks can delegate that part to the github org plugin if you import 

everything's great until folks do `oc delete bc foo`. That deletes the BC and job as users expect. 

The issue is the next time the github org job runs again (via cron, user or by adding a new project), it regenerates the `foo` project again as we list the `|foo|` as a pattern by default.

I grok that its a little clumsy though as its a kinda cross-plugin issue (github org plugin knows nothing about openshift / BuildConfigs). 

We could limit the scope by only doing this on BCs that are annotated as being linked with the github org job maybe? So its not something that happens OOTB; but only on OSIO generated BCs?

**Comment by bparees** [comment]
if the sync plugin were not in the picture, what would the experience be?  User deletes job in jenkins and that automatically removes the pattern from the github org plugin?  (ie how does that pattern normally get removed?)

**Comment by jstrachan** [comment]
AFAIK its a manual step to update the pattern; its just surprising for OpenShift users; then they type `oc delete bc` they don't expect it to just come back again ;)

**Comment by jstrachan** [comment]
We could easily disable this feature OOTB and make it a jenkins configuration option (like the 2 way sync between Jenkins <-> BCs); plus we can use an annotation on the BC to enable this capability?

Maybe a more strategic longer term fix is to get the github org plugin to still work with PRs / webhooks and not require a pattern at all; then we could try just create Jobs inside the github org folder in the usual way in jenkins-sync-plugin. Its lots more work but is much cleaner longer term

**Comment by bparees** [comment]
I see.  Ok, well I still have fears about the sync plugin becoming the "manage all the jenkins things" plugin, but if the code is sufficiently isolated/modularized I guess it should be ok...

/cc @gabemontero

**Comment by jstrachan** [comment]
@bparees totally understood, thanks! I'd love to move us away from this pattern stuff on the github org folder plugin if we can! Ideally it should be able to just work with the Jobs inside its folder(s)

**Comment by jstrachan** [comment]
I'll wait for this PR to merge https://github.com/openshift/jenkins-sync-plugin/pull/137 (after 3.6 stuff etc) then will rebase on it and submit a PR

**Comment by coreydaley** [comment]
@jstrachan It looks like #137 has merged.  Are you still planning on submitting a pull request or can we close this issue?
