### ISSUE TITLE
Feature request: Automatic registry endpoint for ImageStreams with ConfigMap

### ISSUE THREAD

**Issue by jwmullally** [openshift/jenkins-sync-plugin#148]
My use case requires running locally built custom jenkins slave images with extra parameters (volume claims, privileged), so I need to use ConfigMaps for the templates.

For jenkins-slave ConfigMaps to use locally produced ImageStreams, it looks like the registry address has to be hardcoded in by the user. Would it be possible to somehow handle this automatically? E.g. a dummy "imagestream" field which gets translated to "image", or template string for the registry endpoint etc? This would enable oc templates, yaml files etc to be easily portable.

Currently, templates created from `ImageStreamWatcher` have the Docker registry address automatically populated, due to how they are enumerated with `getAuthenticatedOpenShiftClient().imageStreams().inNamespace(namespace).list()`

Example created from ImageStream with label "role: jenkins-slave"
```
<org.csanchez.jenkins.plugins.kubernetes.ContainerTemplate>              
  <image>172.30.1.1:5000/myproject/jenkins-slave-custom-centos7</image> 
```

**Comment by bparees** [comment]
if i understand the request you're proposing the sync plugin parse the configmap xml content and if it finds an `<imagestreamtag>namespace/imagestream:tag<imagestreamtag>` reference, the sync plugin should attempt to lookup the docker image reference and replace that line with `<image>resolved_dockerimagereference<image>` in the xml, before creating the pod template object?

something along those lines anyway?

**Comment by jwmullally** [comment]
Yep, some mechanism like that would be great

**Comment by jwmullally** [comment]
Either that, or being able to annotate ImageStreams with the pod template configuration. Which ever makes most sense.

**Comment by jwmullally** [comment]
Using a hostname for the registry would mostly remove the need for this feature request.

However, it looks like there are open discussions in OpenShift w.r.t. the registry DNS/routes, so maybe that approach can wait until they are resolved.

--------

FYI for anyone else trying jenkins-slave ConfigMaps with internal docker registry DNS records:

During my own testing with "oc cluster up" when I try to use the registry internal DNS name, I see these failures:
```
<image>docker-registry.default.svc:5000/myproject/jenkins-slave-custom-centos7</image>
```
```
Jun 22, 2017 7:15:57 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
INFO: Container is waiting jenkins-slave-custom-centos7-9a1d2ba5861 [jnlp]: ContainerStateWaiting(message=Get https://docker-registry.default.svc:5000/v1/_ping: dial tcp: lookup docker-registry.default.svc on 8.8.8.8:53: no such host, reason=ErrImagePull, additionalProperties={})
```
```
<image>docker-registry.default.svc.cluster.local:5000/myproject/jenkins-slave-custom-centos7</image>
```
```
Jun 22, 2017 6:56:03 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
INFO: Container is waiting jenkins-slave-custom-centos7-849fff06bd4 [jnlp]: ContainerStateWaiting(message=image pull failed for docker-registry.default.svc.cluster.local:5000/myproject/jenkins-slave-custom-centos7:latest, this may be because there are no credentials on this request. details: (Get https://docker-registry.default.svc.cluster.local:5000/v1/_ping: dial tcp: lookup docker-registry.default.svc.cluster.local: no such host), reason=ErrImagePull, additionalProperties={})
```

`journalctl -u docker -f` on my host shows it is my host docker failing to resolve the cluster internal IP. Adding this line to my `/etc/hosts` made it work, but this is obviously a hack...
```
172.30.1.1 docker-registry.default.svc docker-registry.default.svc.cluster.local
```

**Comment by gabemontero** [comment]
I'm experimenting with the notion of dynamically determining whether "image" setting specified in the xml in the configmap is an imagestream/imagestreamtag, but are missing the registring, and if so then getting the fully qualified docker refs, including registries, and using that for the "image" setting of the pod template I then populate the k8s plugin with.

I should hopefully have a prototype to review by tomorrow afternoon.

**Comment by gabemontero** [comment]
@jwmullally - I'll update this bug once we cut a new version of the plugin on the jenkinsci side and incorporate that version into our openshift jenkins image

of course you can build a version of the plugin from the latest in this repo and install it into your running jenkins instance if that suits your needs

thanks

**Comment by gabemontero** [comment]
ok v0.1.26 of the sync plugin has been cut with the changes previously referenced ... when https://github.com/openshift/jenkins/pull/350 merges, the openshift jenkins centos image on dockerhub should be updated soon after
