### ISSUE TITLE
when can/should we upgrade the pom's dependencies?

### ISSUE THREAD

**Issue by jstrachan** [openshift/jenkins-sync-plugin#160]
I wanted to test things out with recent plugins for workflow + github organisation plugins etc. As I started going down this route I found all kinds of things needs changing (the jenkins version, test framework version, various dependencies etc).

For now for easier testing on jenkins 2 with recent plugin dependencies I'm tempted to use a maven profile for now - but I wondered what we intend to do upstream; should we move to jenkins 2 and recent dependencies?

**Comment by jstrachan** [comment]
if we need to keep supporting older jenkins 1.x installations with the plugin I guess using a profile might be best; then folks can build/test on 1.x or 2.x easily from the same codebase?

**Comment by bparees** [comment]
we've deprecated jenkins v1, we don't need to keep supporting it.

**Comment by jstrachan** [comment]
awesome thanks! that saves me messing about with profiles ;) lemme see if I can get a PR to upgrade dependencies
