### ISSUE TITLE
PodTemplate via ConfigMap should override existing ones

### ISSUE THREAD

**Issue by siamaksade** [openshift/jenkins-sync-plugin#163]
Creating a config map with the pod template should override the existing PodTemplates that are created through scanning the imagestreams otherwise it's not possible the modify the existing ones.

If i create a config map with a pod templates called "maven", I end up having two pod templates called "maven" one of which is created automatically when the plugin scans the imagestreams in the registry.

**Comment by gabemontero** [comment]
fyi ... v0.1.28 of this plugin contains the fix from https://github.com/openshift/jenkins/pull/367 and the openshift centos image on docker hub has that version of the plugin
