### ISSUE TITLE
PipelineJobListener fails to initialize when Sync plugin has been disabled in config UI

### ISSUE THREAD

**Issue by scoheb** [openshift/jenkins-sync-plugin#168]
When the sync plugin has been disabled in the config UI (/configure), the PipelineJobListener fails to startup due to a NPE:

> Failed to instantiate Key[type=io.fabric8.jenkins.openshiftsync.PipelineJobListener, annotation=[none]]; skipping this component
> java.lang.NullPointerException
> 	at io.fabric8.jenkins.openshiftsync.OpenShiftUtils.getNamespaceOrUseDefault(OpenShiftUtils.java:215)
> 	at io.fabric8.jenkins.openshiftsync.PipelineJobListener.init(PipelineJobListener.java:65)
> 	at io.fabric8.jenkins.openshiftsync.PipelineJobListener.<init>(PipelineJobListener.java:53)
> 	at io.fabric8.jenkins.openshiftsync.PipelineJobListener$$FastClassByGuice$$ff6b8e19.newInstance(<generated>)
> 	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
> 	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
> 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
> 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
> 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
> 	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
> 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
> 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
> Caused: com.google.inject.ProvisionException: Unable to provision, see the following errors:
> 
> 1) Error injecting constructor, java.lang.NullPointerException
>   at io.fabric8.jenkins.openshiftsync.PipelineJobListener.<init>(PipelineJobListener.java:52)
> 
> 1 error
> 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:52)
> 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
> 	at hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1.get(ExtensionFinder.java:424)
> 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
> 	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
> 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
> 	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
> 	at hudson.ExtensionFinder$GuiceFinder._find(ExtensionFinder.java:386)
> 	at hudson.ExtensionFinder$GuiceFinder.find(ExtensionFinder.java:377)
> 	at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:477)
> 	at hudson.ExtensionList.load(ExtensionList.java:365)
> 	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:303)
> 	at hudson.ExtensionList.iterator(ExtensionList.java:157)
> 	at jenkins.model.Jenkins.<init>(Jenkins.java:994)
> 	at hudson.model.Hudson.<init>(Hudson.java:86)
> 	at hudson.model.Hudson.<init>(Hudson.java:82)
> 	at hudson.WebAppMain$3.run(WebAppMain.java:235)

It seems that the enabled flag is not checked on startup.

But this led me to see that most of the code does not check this flag...

**Comment by gabemontero** [comment]
So yeah the code depends on GlobalPluginConfiguration using its config listener turning everything off when the plugin is disabled (the watches in particular).  But that dependency is broken for PipelineJobListener because it is a DataBoundConstructor and gets instantiated directly by jenkins, independent of what GlobalPluginConfiguation does.

BuildSyncRunListener is in the same boat.

What is even more curious is that PipelineJobListener does not seem to use the server var or namespaces array it is trying to fill in when the NPE occurs.  The fabric guys must have just used the DataBoundConstructor as a means to instantiate that class and regsiter the ItemListener.

Cooking up some clean up and checks for enablement for these odd balls.

@bparees fyi

**Comment by gabemontero** [comment]
hey @scoheb - I'll probably craft a new sync plugin version at the jenkins update center later this week and cut a new version of the openshift jenkins image, but certainly if you can pull these changes down and try them out, we can reopen and add additional fixes as needed.

**Comment by scoheb** [comment]
great! thanks!

**Comment by gabemontero** [comment]
hey @scoheb - quick heads up, I've initiated creation of the 0.1.29 release of the plugin, which should have the changes from PR 170.

when it is ready later today i'll start the update of the openshift jenkins centos image
