### ISSUE TITLE
Add doc for #137

### ISSUE THREAD

**Issue by arnaud-deprez** [openshift/jenkins-sync-plugin#187]
Hi,

This #137 contains some features that are not documented yet.
I can make it for Secrets sync because I went into the code but it would be nice if you can make as long as it is still fresh in your mind of course :-).

Cheers,

**Comment by gabemontero** [comment]
Per our dev process ...this will be handled under https://trello.com/c/SGvNKyMM/1154-5-make-openshift-secrets-available-in-jenkins-as-credentials-jenkinsintegration which I've been assigned for next sprint (starting Monday).

**Comment by arnaud-deprez** [comment]
Thank you for the information :-)
