### ISSUE TITLE
java.lang.NoSuchMethodError: io.jenkins.blueocean.rest.factory.BlueRunFactory.all()Lhudson/ExtensionList

### ISSUE THREAD

**Issue by arnaud-deprez** [openshift/jenkins-sync-plugin#191]
Hi,

I'm using Openshift v3.7.1 with minishift and I customized a jenkins image to use the latest blueocean feature (1.3.5) and I got the following exception: 

```
Jan 17, 2018 8:27:03 AM hudson.triggers.SafeTimerTask run
--
  | SEVERE: Timer task io.fabric8.jenkins.openshiftsync.BuildSyncRunListener$1@431a265e failed
  | java.lang.NoSuchMethodError: io.jenkins.blueocean.rest.factory.BlueRunFactory.all()Lhudson/ExtensionList;
  | at io.fabric8.jenkins.openshiftsync.BuildSyncRunListener.pollRun(BuildSyncRunListener.java:211)
  | at io.fabric8.jenkins.openshiftsync.BuildSyncRunListener.pollLoop(BuildSyncRunListener.java:198)
  | at io.fabric8.jenkins.openshiftsync.BuildSyncRunListener$1.doRun(BuildSyncRunListener.java:157)
  | at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
  | at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
  | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  | at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
  | at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
  | at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
```

You can test it with my image here: https://github.com/arnaud-deprez/jenkins-docker-openshift/tree/master/2

Apparently the method all() has been removed in this commit: https://github.com/jenkinsci/blueocean-plugin/commit/4cefa8d4a94bb513d252e436ae8228f809368209#diff-de2c99c1b83fcb1b1ab54d48ce956026

I don't have much time now to investigate further on this and as I don't know this blueocean-api, it can take time to git in it and replace this code by an appropriate one.

Can someone who knows it better than me can have a look ?

Thank you!

**Comment by gabemontero** [comment]
OK short term we can place that block in a try / catch.  This path can survive if we can't obtain a BlueRun object.

Longer term when the base openshift jenkins image upgrades its blueocean dep we can see about finding what alternative was provided for BlueRunFactory.all()

Their public API contract is certainly loose

**Comment by gabemontero** [comment]
@arnaud-deprez you can manually build the plugin with this fix in the interim

I'll update / reference this issue when I update the openshift jenkins centos image ... should be later today or tomorrow

**Comment by arnaud-deprez** [comment]
@gabemontero ok thank you!
Any idea when it will be included in the redhat image or where I can track it ? Because I'm using in a customer and it's important for them to use rhel instead of centos.

**Comment by gabemontero** [comment]
longer pathway for that @arnaud-deprez 

standard procedure, I update the openshift jenkins repo master branch, and the bump in plugin version will be in the next upcoming release (3.9); I can't seem to access the schedule pages for that from my home vpn currently, but I think we are talking sometime in March

next level, I update the 3.7 branch, assuming the change is tolerable as is there (it is in this case) and it comes out with the next 3.7 errata;  I'm told that is in roughly 3 weeks intervals

**Comment by arnaud-deprez** [comment]
Ok good! 
If you can let me know here or attach a link to your issues tracker, it would be nice (like trello ?).
Have a nice day!
