### ISSUE TITLE
1.0.0 Is Showing Odd Visuals

### ISSUE THREAD

**Issue by sherl0cks** [openshift/jenkins-sync-plugin#194]
Visualization is out of order. sync plugin 1.0.0 and OCP v3.7.14

![screenshot from 2018-01-24 19-44-34](https://user-images.githubusercontent.com/1335137/35368198-568f33da-013f-11e8-8afb-ace6a24c735a.png)

![screenshot from 2018-01-24 19-44-54](https://user-images.githubusercontent.com/1335137/35368194-53009c54-013f-11e8-8a99-8baa8b10ce6f.png)

**Comment by gabemontero** [comment]
ok the input required caught my eye ... I found a sample pipeline we have that prompts for input, and saw similar behavior in the openshift ui pipeline display (and discrepancy with the analogous blueocean display).

the first point, which is good news (at least for me ;-) ) is I see this ordering anomaly with prior versions of the plugin; so there is not a regression

also, I see in your two examples that only the bottom has a "Deploy to Demo" stage where it is noting the request for input; the "Deploy to Dev" seems to show up in the same spot for both; was that recent add ?

wrt prompting for input, we recently noted those stages in a separate annotation for the openshift UI;  I'll have to check with that team, but I suspect they are not as of yet accounting for that

**Comment by sherl0cks** [comment]
@gabemontero I do not see this behavior in version `0.1.32`, which I consider the last stable version of the plugin. IMHO - regardless whether this happened in `0.9.1`, `0.9.2` or `1.0.0`, this is a serious regression and renders these versions of the plugin unusable for customers.

RE: the stages, no, these are two pics of the same run of the same pipeline. The fact that they visually do not make sense is the core of this issue.

**Comment by sherl0cks** [comment]
If you would like a sample pipeline or plugins.txt to reproduce, let me know.

**Comment by gabemontero** [comment]
ok I'll revert to `0.1.32` and see if the behavior changes for the test I was referring to; based on those results, we'll see if I need your repro

I'll also defer on my opinion of the severity and implications until I have that data, but this will be a focus of mine later today, so it is at least high on my priority queue

**Comment by gabemontero** [comment]
oh forgot to clarify my focus on the prior version stuff ... I was initially worried that the bump in blueocean version in the jenkins image (which lead to the change between 0.9.2 and 1.0.0) was the cause ... but that is not the case.

the "was working fine on 0.1.32" point actually might lend some weight to my initial theory around the changes for the pending input annotation ... but I should be able to determine with certainty once I get data around the json produced for the annotation at the 0.1.32 level.

thanks

**Comment by gabemontero** [comment]
sure enough the json is different with 0.1.32 or this plugin (and 1.1.6 of blueocean, though we don't access blueocean for building the json at 0.1.32) ... the order of the stages lines up with our sample which prompts for input

comparing the two versions of logic now ...

**Comment by gabemontero** [comment]
yep found the cause - related to the declarative pipeline fix https://github.com/openshift/jenkins-sync-plugin/commit/26bb931185c18dcf1027661bbfba5ebf59924f7d ... I was able to revert to the correct behavior by removing one line with the latest code; but I have to iterate some more to re-enable that fix but still preserve the stage order for the openshift UI to process (they just go over the stage list, ignore the start date).

I should have a PR / new version / image update sometime tomorrow

have some ideas on an update to the extended test to catch this in the future .. that will follow

**Comment by gabemontero** [comment]
v1.0.1 of the sync plugin has the fix for this and is cooking in jenkins land

I'll be starting the image update process when it is available
