### ISSUE TITLE
Any way to disable TLS verification?

### ISSUE THREAD

**Issue by rameezk** [openshift/jenkins-sync-plugin#202]
Is there any way to ignore SSL errors when using the plugin? We want to ignore SSL errors in our testing environments.

**Comment by gabemontero** [comment]
Hey @rameezk - sorry, but skip tls / trust tls is not a connection option currently supported.

We do support that with some of other plugins, so I see no issue in adding it.  It would just be a prioritization exercise as to when.

@bparees - opinions on whether we open a card for this vs. just do it on the side?

**Comment by bparees** [comment]
@gabemontero card

**Comment by gabemontero** [comment]
OK https://trello.com/c/YWx3ihnp/1495-allow-skip-tls-for-sync-plugin-jenkinsintegration-pipelineintegration opened.

@rameezk - per our process, I'm closing this issue.  If you would like to chime in on priority, track the progress of this, you can join our trello board:  https://trello.com/b/wqe9UaaZ/developer-experience
