### ISSUE TITLE
RFE: Link to Blue Ocean UI from OCP Pipeline UI

### ISSUE THREAD

**Issue by sherl0cks** [openshift/jenkins-sync-plugin#203]
When input is required to a pipeline (see bottom right of screen shot), I would like it to redirect to the blue ocean view, not the default jenkins view. I'm suspecting the sync plugin provides the URI to the OCP UI, thus why I opened the issue here. Let me know if it needs to move. Since the Jenkins image now has blue ocean this should be a safe operation, although error handling / configuration might be needed to enable the old jenkins UI links.

![screenshot from 2018-02-15 16-59-00](https://user-images.githubusercontent.com/1335137/36285536-936021b4-1271-11e8-9d85-d1e659112d26.png)

**Comment by gabemontero** [comment]
this is the right spot @sherl0cks 

yep, this was a somewhat recent add-on from our friends on the fabric/OSIO side, @rupalibehera in particular.

Assuming we can get the URL from the BlueRun data, I would image fabric/OSIO would be OK with redirecting to the blue ocean view.  But we'll need to confirm.

**Comment by sherl0cks** [comment]
@gabemontero OK - so long that it is technically possible, then it likely makes sense to have a configurable switch on the plugin to send you to the old view. this would be a big improvement in UX for customers - leaving OCP UI and going to the old Jenkins feels like going back 15 years in time.

**Comment by sherl0cks** [comment]
@gabemontero what do we need to do get this in the dev queue? feels like low hanging from to get a big UX improvement

**Comment by gabemontero** [comment]
Hey @sherl0cks 

Took at look at this and it is not turning out to be some easy/low hanging fruit type of work.  I used the bluegreen pipieline at https://github.com/openshift/origin/blob/master/examples/jenkins/pipeline/bluegreen-pipeline.yaml for reference.

I'm not finding analogous API in the BlueRun* set of api from the blueocean-rest component to what is available with `PendingInputActionsExt`and `RunAPI.getInputStepSubmitUrl`

I took at stab at looking at the HTTP flows via the chrome dev tools when you hit the Proceed/Abort button in blueocean, and best as I can tell, it gets somehow wired to the whatever step in the model's parsed output of the pipeline the prompt call happens to occupy, all buried in the javascript for those buttons.  The step url itself is not exposed.

At best, I think our UI would simply have to post to the run on blue ocean as noted by the `openshift.io/jenkins-blueocean-log-url` and then use would happen to see the buttons.

I'll pull in a couple of folks for questions:
a)  @rupalibehera  - do you remember looking to sending users to the blueocean side of things when you first code up user prompt feature in the plugin

b) @spadgett - any chance you or someone on your team compared how blueocean does proceed/abort with how we ended up doing it once we started providing the `openshift.io/jenkins-pending-input-actions-json` annotation ... I  guess as much as anything I'm looking for a confirmation of a) how I'm interpreting the blue ocean UI (web console dev is not my forte) and b) how does the notion of simply putting the current contents of `openshift.io/jenkins-blueocean-log-url` into a new pending intput annotation, and the user will see the prompt from blueocean and go from there, sound to you ?

Not sure if that last idea really holds water

Pending insight from those two folks @sherl0cks, I'm not currently optimistic a quick resolution is in the cards here

**Comment by sherl0cks** [comment]
@gabemontero thanks for looking into. this is still high value work, even if it is more effort. hope we can get some good info from @rupalibehera and @spadgett

**Comment by akram** [comment]
+1

**Comment by gabemontero** [comment]
Created https://trello.com/c/PHbWyP6J/1589-5-link-to-blue-ocean-ui-from-ocp-pipeline-ui to track

**Comment by chriscarpenter12** [comment]
Is it possible to get the `View Log` link to use the `openshift.io/jenkins-blueocean-log-url` value?
