### ISSUE TITLE
Listening to multiple namespaces with prefix/regex/ALL?

### ISSUE THREAD

**Issue by jimmychu0807** [openshift/jenkins-sync-plugin#205]
Hi,

We have two openshift clusters deployed, one is UAT, and another PROD. Our developer will create Jenkins buildpipeline, and by default, we would like to have our externally-configured Jenkins to listen to all these projects and build for them. 

Instead of having developers specified the namespace one by one and let the Jenkins admin know to add them. Is it possible to specify namespace as ALL namespaces, or namespace with certain prefix / regular expression?

Thanks.

**Comment by bparees** [comment]
I don't believe it's currently possible.

wildcarding the set of namespaces to sync raises several challenges:

1) the jenkins SA would need permissions to list all namespaces so it can filter (this is a relatively high level permission to grant that most users running jenkins would not have)
2) the jenkins SA would need to watch namespaces so when new ones are created/deleted that match the wildcard, they get removed from what the sync plugin is tracking.

**Comment by jimmychu0807** [comment]
@bparees Thanks for explaining. I guess there isn't much I can do now (except contributing to the codebase, of course).
