### ISSUE TITLE
Abililty to run this plugin as a sidecar for remote/shared Jenkins support

### ISSUE THREAD

**Issue by david-martin** [openshift/jenkins-sync-plugin#212]
**What**
Allow the logic in this plugin to run outside of Jenkins i.e. in a sidecar

**Why**
So that I can use a single shared Jenkins cluster from multiple namespaces in OpenShift.

**Suggestions**
The sidecar could re-use the logic in this plugin, but run as a standalone Java process.
The process runs in the User's namespace, but has the URL & credentials for accessing the remote Jenkins via it's API.
It can also use a Service Account (as it does now) to watch BuildConfigs, Builds etc.. in the same namespace and sync them to Jenkins via the API.

Here's how the end to end might work with this approach in OpenShift.
* From the Catalog, have an additional Jenkins ServiceClass that is used to provide the user with access to an already existing Jenkins cluster.
* When you 'provision' this via the Catalog, it prompts for the location of the Jenkins cluster, and admin credentials
* An APB could be used with a provision task that does the following:
  * creates a new non-admin account in the remote Jenkins (the new account credentials are ultimately stored in a secret by the Catalog when provision finishes)
  * provisions a serviceaccount & the jenkins sync sidecar in the current namespace
* The sidecar continuously sync BuildConfigs, Builds etc.. to Jenkins, and Build metadata in Jenkins back to Build annotations in OpenShift.

**Questions/Considerations**
* Does Jenkins have any concept of multi-tenancy or restricting jobs to specific users?
* How will auth work? Currently the Jenkins login plugin will allow anyone in a specific namespace with 'view', 'edit' or 'admin' permission for that namespace to have some level of access to the Jenkins cluster. Related to multi-tenancy, but can Jenkins lookup specific permissions depending on the Jobs the user wants to access?

@gabemontero Would appreciate your thoughts on this.
It's something we'd be looking at doing eventually in the context of having a shared Jenkins with specific hardware nodes/slaves that can be re-used across multiple projects.
The specific hardware could be Mac for doing iOS builds, or Windows instances for Windows Phone or Xamarin builds.

(cc @weileylee @maleck13 for visibility)

**Comment by bparees** [comment]
The sync plugin is heavily dependent on being inside the jenkins process so it can directly invoke local apis.  What you're proposing would have to be an entirely new project(even if it borrowed heavily from the sync plugin) and not something I see us pursuing anytime soon.

Also not clear why you can't get what you need by:

1) running a single jenkins master w/ the sync plugin
2) configuring the sync plugin to watch multiple namespaces
3) configuring your jobs(triggered by the sync plugin) such that they run on jenkins slaves running on the various specific hardware configurations you need

**Comment by david-martin** [comment]
Thanks for the response @bparees.

> What you're proposing would have to be an entirely new project(even if it borrowed heavily from the sync plugin) and not something I see us pursuing anytime soon.

Hmm, yeah, that makes sense. Good point. Based on that alone, this issue can be closed.
Good to see where the discussion goes as to how best to solve our problems.

> configuring the sync plugin to watch multiple namespaces

I did not know this was possible :+1: I think that's a good way of solving the syncing from multiple projects.

Are you aware of any multi-tenancy features/support in Jenkins that could help with ensuring a user only sees the Jobs in jenkins that map back to Build Configs in their OpenShift namespace?

**Comment by bparees** [comment]
> Are you aware of any multi-tenancy features/support in Jenkins that could help with ensuring a user only sees the Jobs in jenkins that map back to Build Configs in their OpenShift namespace?

Not aware, no.  Assuming it is even possible within the jenkins auth framework, you'd probably have to rely on jenkins local user management to implement it today as the openshift login/oauth plugin is not going to be sophisticated enough to manage multitenancy in that way.

**Comment by gabemontero** [comment]
So @bparees is a much better multi-tasker than myself, as he managed to weigh in on this a midst all the 3.9 GA fire fighting we've been doing ;-) ....

I only have a couple of minor things to add:
- to help facilitate setting up multi-namespace, we have [this card](https://trello.com/c/V1mtI7bi/1518-3-allow-the-use-of-environment-variables-in-addition-to-tell-which-namespaces-sync-plugin-should-monitor-jenkinsintegrationpipel ) for specifying the namespaces via env var that you want sync plugin to monitor ... you still have to deal with making sure the SA mounted in the pod or whatever other creds your are using have the permissions

- only seeing jobs in your namespace  ... hadn't thought of that before, but after some quick searching it seems possible from a general Jenkins perspective, though our images / plugins are not set up for it yet 

See https://support.cloudbees.com/hc/en-us/articles/204173600-How-do-I-limit-users-access-to-the-folders-to-which-they-belong-to-

We would to bring in those plugins into our images, minimally sort out the new Jenkins permissions they introduce, possibly need to sort out how the RBAC plugin changes the game wrt how we plug into the jenkins authorization support today, and then we could see about mapping openshift namespace roles to jenkins ones

Definitely a card (close to the R&D variety) on [our board](https://trello.com/b/wqe9UaaZ/developer-experience) would be needed to prioritize work on such  feature, as this is not something we can do in any sort of "in between things" fashion.

**Comment by david-martin** [comment]
Thanks @gabemontero.



> only seeing jobs in your namespace ... hadn't thought of that before, but after some quick searching it seems possible from a general Jenkins perspective, though our images / plugins are not set up for it yet
> 
> See https://support.cloudbees.com/hc/en-us/articles/204173600-How-do-I-limit-users-access-to-the-folders-to-which-they-belong-to-

Interesting, I'll take a look at this to see how it could help.



> Definitely a card (close to the R&D variety) on our board would be needed to prioritize work on such feature, as this is not something we can do in any sort of "in between things" fashion.

I think this is something we (aerogear mobile team) would look to find/implement a solution to if/when we decide it's a requirement to support a shared Jenkins for mobile app builds.
Good to know what the roadmap is for this plugin, and potential solutions on the multi-tenancy and multi-namespace side.
