### ISSUE TITLE
Build pruning not supported

### ISSUE THREAD

**Issue by brix4dayz** [openshift/jenkins-sync-plugin#241]
Recently, we encountered an issue where one of our Jenkins projects had amassed a few hundred builds. This caused the OpenShift API server to panic when an end user would go to the project and view the pipeline builds (https://access.redhat.com/support/cases/#/case/02098610).

As a result, we were looking into how prune pipelines builds according to OpenShift and found this in the [docs](https://docs.openshift.com/online/dev_guide/builds/advanced_build_operations.html#build-pruning). However, it looks like `successfulBuildsHistoryLimit`/`failedBuildsHistoryLimit` isn't supported for the pipeline strategy. You can recreate it with the following BuildConfig and running the pipeline several times. Note, I had to `oc apply` the BuildConfig a second time in order for build history fields to be applied to the object's YAML, initially it seemed like they were ignored:

```
---
kind: BuildConfig
apiVersion: v1
metadata:
  name: build-pipeline
spec:
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 2
  runPolicy: Parallel
  strategy:
    type: Pipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('master') {
          stage 'Questionable'
          echo "Look at me I'm an unstable build"
          randomInt = (new Random()).nextInt(2)
          if (randomInt < 1 ) {
            echo "Random Int ${randomInt} is 0!"
          } else {
            echo "Random Int ${randomInt} is 1..."
            currentBuild.result = 'FAILURE'
          }
        }
```

If you run the pipeline several times it will keep all the Build's rather than just the most recent two successes and failures.

The way I'm imaging it would work is only prune's the OpenShift builds but leaves the actual builds on Jenkins untouched. The Jenkins build pruning can be managed through the pipeline properties such as:

```
properties([
   durabilityHint('PERFORMANCE_OPTIMIZED'),
   buildDiscarder(logRotator(daysToKeepStr: '90'))
])
``` 

However, if the BuildConfig featured time-based build pruning which would configure the build discarder on Jenkins that'd be ideal.

**Comment by bparees** [comment]
we are actually adding support for pruning pipeline builds in v3.11:
https://github.com/openshift/origin/pull/19639

(note that 3.10 is the next release, so this will be after that).
