### ISSUE TITLE
RFE: Make Namespaces list configurable via environment variables

### ISSUE THREAD

**Issue by brix4dayz** [openshift/jenkins-sync-plugin#242]
As of now, the only way to configure the Namespace list is through the UI according to the README:

> By default, the project running Jenkins is monitored, but additional projects can be monitored by adding them to the Namespace list in the "Manage Jenkins" -> "Configure System" section for this plugin. NOTE: the service account associated with the Jenkins deployment must have the edit role for each project monitored

However, the sync plugin (and the jenkins image itself) enable us to provision our Jenkins instances immutably for the most part. We'd like this Namespace list to be configurable through an environment variable we could set on our deployment of the Jenkins master to make this more streamlined.

**Comment by gabemontero** [comment]
Hey @brix4dayz - yep, and long standing req.

We are tracking it per our process via https://trello.com/c/V1mtI7bi/1518-3-allow-the-use-of-environment-variables-to-specify-namespaces-sync-plugin-should-monitor-jenkinsintegrationpipelineintegration

Feel free to join our trello board and chime, track, etc.

**Comment by brix4dayz** [comment]
I'll start checking trello first before I keep bugging you guys, thank you!
