### ISSUE TITLE
Update docs to encourage use of ConfigMap

### ISSUE THREAD

**Issue by alanbchristie** [openshift/jenkins-sync-plugin#246]
Related to issue #245, Gabe Montero mentioned...

> We should update our docs to encourage folks to use the ConfigMap approach if they are modifying the PodTemplate config beyond the basics we employ.

Not sure whether this comment warrants an issue but I've created one to track this suggestion as the adjustment of agent configurations beyond their defaults currently appears to be vulnerable to background updates.

**Comment by gabemontero** [comment]
This might only be a PR in the openshift-docs but I'll cross reference what we have there with the README here and decide what text should go where
