### ISSUE TITLE
Is it possible to exclude some path from webhook trigger?

### ISSUE THREAD

**Issue by samush** [openshift/jenkins-sync-plugin#249]
Hello,

Please give me advice if it possible to make behavior similar to this option in Jenkins job:
![image](https://user-images.githubusercontent.com/35532750/43679751-78e40b64-9833-11e8-8e3b-df065c040c31.png)
We have a few projects in single Bitbucket repo and for now every commit triggers all jenkins job that was synced from BuildConfig objects.
I am using Openshift Origin 3.9, Jenkins master from template (version 2.121.2) and Jenkins-sync-plugin version 1.0.24
Example of BuildConfig:

apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: objectmanagement.dev
  namespace: jenkins
spec:
  source:
    contextDir: BusinessLogicLayer/ObjectManagement/Service/Server
    git:
      ref: dev
      uri: https://bitbucket.org/techdev/platform
    sourceSecret:
      name: bitbucket-jenkins
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile.buildAndPublishDev
    type: JenkinsPipeline
  triggers:
  - bitbucket:
      secretReference:
        name: bitbucket-webhook
    type: Bitbucket

---
Thanks for any help
Alex.

**Comment by bparees** [comment]
this is really more an openshift question than a jenkins sync plugin question, but the answer is no, it's not possible to filter the webhook commit trigger based on the specific path that was changed in the commit, it is only possible to filter based on the branch that was changed.  We recommend you use the more sophisticated jenkins triggering if you need that level of filtering.

this is described here:
```
When the push events are processed, the OKD master host confirms if the branch reference inside the event matches the branch reference in the corresponding BuildConfig. If so, it then checks out the exact commit reference noted in the webhook event on the OKD build. If they do not match, no build is triggered.
```
https://docs.okd.io/latest/dev_guide/builds/triggering_builds.html#webhook-triggers

**Comment by samush** [comment]
Ok, thanks for advice!
