### ISSUE TITLE
Duplicate Pipeline Run's

### ISSUE THREAD

**Issue by rhnewtron** [openshift/jenkins-sync-plugin#260]
Hello,

I have the following Openshift 3.9 setup: 

- 1 CICD Namespace
  - Runs the Jenkins instance (manually provisioned, autoprovisioning disabled in master-config.yaml)
  - Note: There is only ONE Jenkins running in Openshift watching multiple namespaces
- 2 Project Namespaces
   - Petclinic
     - Contains one Build Job (spring-petclinic-source-ngp)
   - Petclinic2
     - Contains one Build Job (spring-petclinic-source-1ew)

Jenkins is configured with

- OpenShift Sync Plugin 1.0.28
- Stash Notifier Plugin 1.14
- Jenkins watches the namespaces "petclinic" and "petclinic2" with the Symc Plugin

![image](https://user-images.githubusercontent.com/40258627/45623223-e1b63980-ba86-11e8-9232-0121d53c4610.png)

When I run the pipeline in one Project (petclinic), triggered via the Openshift GUI, actually 2 Builds are triggered in Jenkins.  What is the issue here ?

![image](https://user-images.githubusercontent.com/40258627/45623127-8f751880-ba86-11e8-9064-2bd8695e3ef1.png)
![image](https://user-images.githubusercontent.com/40258627/45623130-92700900-ba86-11e8-886c-e9810a6ea6da.png)

**Comment by gabemontero** [comment]
OK I was unable to reproduce this.  I did:
0) 3.9 openshift. v1.0.28 sync plugin
1) only 1 jenkins in its own namespace monitoring all the namespaces/projects with  
2) app projects with the same prefix for the name (1 of the projects has just the prefix .. even tried that with more project with different suffixes for the names
3) created pipieline bc's with the same prefix for a name, with a small suffix that varies 

@rhnewtron - could you provide
a) the yaml for the pipeline bc's in questions
b) the logs for the jenkins pod 

And I'll see if I can discern any differences .... also the jenkins logs from your repro might have definitive info regardless

thanks

**Comment by rhnewtron** [comment]
I restarted the Jenkins Server and now only one build is triggered. So this may be a very strange issue. However I think we can close it, as the restart fixed it.
