### ISSUE TITLE
adding option to specify custom credential name

### ISSUE THREAD

**Issue by seldon007** [openshift/jenkins-sync-plugin#271]
HI

We got a lot of existing pipelines with Jenkins Credentials ID's baked into them and they do not match the predefined name: namespace-secretname
Maybe add the option for custom names e.g. by annotation or label on the secret?

**Comment by gabemontero** [comment]
Hey @seldon007 

An annotation to customize the name sounds reasonable.  The annotation name should start with `jenkins.openshift.io/`.  And an update to the README to announce the feature.  It would be an update to https://github.com/openshift/jenkins-sync-plugin/blob/master/src/main/java/io/fabric8/jenkins/openshiftsync/CredentialsUtils.java#L198-L200 to factor in the annotation into the name generation. 

My team doesn't have the bandwidth to work on such a feature at this time, but if you are willing to submit a PR with the changes I noted above, I'll review and merge an acceptable version of it.

thanks

**Comment by seldon007** [comment]
I not really a developer but I will have a look at it and see if it is above my paygrade :-)

**Comment by waveywaves** [comment]
@gabemontero @seldon007 I would like to work on this issue if that is alright. Anything I need to keep in mind before I start ?

**Comment by gabemontero** [comment]
hey @waveywaves - PRs are certainly welcome

I can not think of any other input besides what I provided in https://github.com/openshift/jenkins-sync-plugin/issues/271#issuecomment-437971158

Start there and then we can iterator once you have the PR up.

**Comment by waveywaves** [comment]
@gabemontero I am working on this. Please do assign this to me.

**Comment by gabemontero** [comment]
good news @waveywaves - unfortunately, the github permissions are set such that I cannot set assignees to anyone outside the openshift org

but don't worry, we'll let you have at it, and your name of course will be on the PR and commit
