### ISSUE TITLE
PodTemplates for tagged ImageStreams not added

### ISSUE THREAD

**Issue by sabre1041** [openshift/jenkins-sync-plugin#278]
ImageStreams with the label `role=jenkins-slave` are not being added properly when tags are utilized. 

Logic appears to only check for key/value pair on annotation whereas the key/value appears only on the ImageStreamTag.

**Comment by bparees** [comment]
@sabre1041 can you provide the yaml for your imagestream?

**Comment by bparees** [comment]
the logic to check ISes is here:
https://github.com/openshift/jenkins-sync-plugin/blob/master/src/main/java/io/fabric8/jenkins/openshiftsync/ImageStreamWatcher.java#L237

along with the logic to check for annotations:
https://github.com/openshift/jenkins-sync-plugin/blob/master/src/main/java/io/fabric8/jenkins/openshiftsync/ImageStreamWatcher.java#L252-L267

so i'm surprised one would be working but not the other.

**Comment by gabemontero** [comment]
Yeah when we implemented this feature, we encountered errors like this while trying to use labels with imagestreamtags:

```
gmontero ~ $ oc label imagestreamtags jenkins:2 foo=bal -n openshift
The ImageStreamTag "jenkins:2" is invalid: metadata: Invalid value: "": may not update fields other than metadata.annotations
gmontero ~ $ 
```

Where as it worked with imagestreams:

```
gmontero ~ $ oc label imagestream jenkins foo=bal -n openshift
imagestream.image.openshift.io/jenkins labeled
gmontero ~ $ 
```

And annotations worked with imagestreamtags:

```
gmontero ~ $ oc annotate imagestreamtags jenkins:2 foo=bal -n openshift
imagestreamtag.image.openshift.io/jenkins:2 annotated
gmontero ~ $ 
```

So per the links @bparees noted, we check the labels on imagestreams, and annotations on imagestreamtags.

The difference is noted in the doc at https://docs.okd.io/latest/using_images/other_images/jenkins.html#configuring-the-jenkins-kubernetes-plug-in

The above was even with the latest 4.0 code, though the same thing occurred when developing this feature.

If there is some alternative, relatively mainstream way, for users to reliably set labels on imagestreamtags, we can change things to solely labels, or still support annotations for ISTs for migration purposes, but also support labels.

**Comment by sabre1041** [comment]
@bparees @gabemontero Labels applied to ImageStreams are propagated to ImageStreamTags. So for example if an existing image only contains tags other than `latest`, Jenkins will never be configured to resolve the proper tag. In addition, in a similar vein, if a custom image is built that utilizes a tag other than latest, it also will not be resolved.

There should still be a check for labels applied to ImageStreamTag's for `role=jenkins-slave` even though users themselves cannot apply labels after the fact. 

The referenced PR from the [containers-quickstarts](https://github.com/redhat-cop/containers-quickstarts/pull/142) repository illustrates this use case.

**Comment by gabemontero** [comment]
Finally got back to this ... PR up

**Comment by gabemontero** [comment]
Will tweak docs in separate PR

**Comment by gabemontero** [comment]
v1.0.35 of the plugin has been initiated with this fix

**Comment by gabemontero** [comment]
hey @sabre1041 - so v1.0.35 of the sync plugin is up at the jenkins update center at https://updates.jenkins-ci.org/download/plugins/openshift-sync/

Given where we are in the 4.0/4.1 dev cycle, and the available workaround, I'm inclined to wait to pull in this change until later to afford it more evaluation.  We should get a fair amount from our users in legacy jenkins shops that pull that latest plugins from the update center into their standalone jenkins.  But it has only been a couple of days.

So,
a) are you in accordance with such priority?
b) out of curiosity, would it be possible for the change to be smoked tested in any upcoming labs or internal testing your group would be doing?

thanks

**Comment by gabemontero** [comment]
FYI ... I've gotten some tangential feedback from some users (including RH subscribers) with v1.0.35 and PodTemplates, and we seem to be good to date.

So I'll be pulling this into my next image update later today.  It will not be part of 4.1.0 GA, but will get into the z stream.
