### ISSUE TITLE
Scan for PodTemplates from another namespace without syncing other objects

### ISSUE THREAD

**Issue by bstinsonmhk** [openshift/jenkins-sync-plugin#280]
Say I have a team that controls a set of Jenkins slave images in one namespace, and wants to provide them for folks to use in jenkins instances in their own namespaces. We probably wouldn't want to directly point the plugin from all of those instances to sync the central agent namespace. 

Would it make sense to add a config option specifying a namespace to scan only for slave images, and perhaps to scan the openshift/ namespace by default as well?

**Comment by gabemontero** [comment]
Actually housing shared resources in a common namespace is something we promote @bstinsonmhk ... even with the jenkins per namespace scenario with sync plugin.

Scanning the openshift namespace by default was discussed when introducing pod templates from imagestream/imagesstreamtags but was rejected.  Haven't seen enough cause yet to change from that.

thanks
