### ISSUE TITLE
Duplicate secret with custom name is created after providing the annotation or the same

### ISSUE THREAD

**Issue by waveywaves** [openshift/jenkins-sync-plugin#301]
Custom names are only applied if the annotation for overriding the secret name `jenkins.openshift.io/secret.name` is given before the custom name is labelled with `credential.sync.jenkins.openshift.io=true` else the secret name is not updated.

**Reproducing the behaviour**

1> Create the secret and label it
``` sh
$ cat jenkins-sync-test-secret.txt
name=whatsthereinit

$ oc create secret generic testsecret --from-file=filename=jenkins-sync-test-secret.txt 
secret "testsecret" created

$ oc label secret testsecret credential.sync.jenkins.openshift.io=true
secret "testsecret" labeled
``` 
![Screenshot from 2019-04-15 15-08-35](https://user-images.githubusercontent.com/11972233/56122668-8b639780-5f90-11e9-83e4-9a94bc3a29a0.png)

2> Annotate it 
```sh
$ oc annotate secret testsecret jenkins.openshift.io/secret.name=testsecretnewname
```
_Jenkins pod log_
```
Apr 15, 2019 8:38:13 AM io.fabric8.jenkins.openshiftsync.CredentialsUtils upsertCredential                                    INFO: Updated credential vibhav-jenkins-testsecret from Secret
NamespaceName{vibhav-jenkins:testsecret} with revision: 2687565
```
![Screenshot from 2019-04-15 15-11-46](https://user-images.githubusercontent.com/11972233/56122819-e5645d00-5f90-11e9-9dfe-6c70d32d2f33.png)

A duplicate secret is created with the new name instead of overriding the previous secret.

**Comment by gabemontero** [comment]
were you planning to circle back to fixing this in the relative near term @waveywaves , or do you need to to take it on?

good investigation by the way :-)
