### ISSUE TITLE
Document plugin handling of non-existent namespaces

### ISSUE THREAD

**Issue by andyfeller** [openshift/jenkins-sync-plugin#315]
In administering the openshift-sync plugin usage, we've manually blocked changes to see if namespaces exist because we know the plugin doesn't handle non-existent namespaces, however we don't know if it will eventually recover when namespace is created.  Rather than scouring the underlying code and inferring the expectation, it would be more appropriate to document the official behavior.

**Comment by waveywaves** [comment]
Hello Andy ! Could you maybe give an example for this. Not sure if I understand it correctly. 
/assign waveywaves

**Comment by andyfeller** [comment]
Hey @waveywaves,

There are 2 scenarios we've found where the openshift-sync plugin threads die and require an individual to re-save Jenkins configuration to restore them.

1. Syncing namespaces that don’t exist
2. Syncing namespaces that Jenkins doesn’t have access to

Whether the plugin could be updated to support these better or not, the plugin documentation should explain the expectations around namespaces.
