### ISSUE TITLE
BuildToActionMapper is not populated

### ISSUE THREAD

**Issue by waveywaves** [openshift/jenkins-sync-plugin#332]
While working on https://github.com/openshift/jenkins-sync-plugin/pull/325/ I noticed that [class BuildDecisionHandler](https://github.com/openshift/jenkins-sync-plugin/blob/master/src/main/java/io/fabric8/jenkins/openshiftsync/BuildDecisionHandler.java) and [class BuildToActionMapper](https://github.com/openshift/jenkins-sync-plugin/blob/master/src/main/java/io/fabric8/jenkins/openshiftsync/BuildToActionMapper.java) are never used. They are supposed to function the way [class BuildConfigToJobMap](https://github.com/openshift/jenkins-sync-plugin/blob/master/src/main/java/io/fabric8/jenkins/openshiftsync/BuildConfigToJobMap.java) / [class BuildConfigToJobMapper](https://github.com/openshift/jenkins-sync-plugin/blob/master/src/main/java/io/fabric8/jenkins/openshiftsync/BuildConfigToJobMapper.java) initialize the `BuildConfigToJob` Map making it easier for functions to pick out the corresponding `WorkflowJob` for consumption.

I noticed this when I was trying to query https://github.com/openshift/jenkins-sync-plugin/blob/master/src/main/java/io/fabric8/jenkins/openshiftsync/BuildToActionMapper.java#L27 to override the `BuildCause` for a particular `Build`.

`BuildSyncRunListener` is home `upsertBuild` and needs some refactoring as well. Similar to what we did for `upsertJob`.

cc @akram @gabemontero

**Comment by gabemontero** [comment]
On Sat, Aug 24, 2019 at 7:33 AM Vibhav Bobade <notifications@github.com>
wrote:

> While working on #325
> <https://github.com/openshift/jenkins-sync-plugin/pull/325> I noticed
> that class BuildDecisionHandler
> <https://github.com/openshift/jenkins-sync-plugin/blob/master/src/main/java/io/fabric8/jenkins/openshiftsync/BuildDecisionHandler.java>
>
BuildDecisionHandler is what allows you to trigger a pipeline build from
the jenkins console.

The jenkins core looks for extensions like it when you start a build from
the console.

You can’t get rid of it.

**Comment by waveywaves** [comment]
@gabemontero Thanks for that :) I noticed that buildToCauseMap in https://github.com/openshift/jenkins-sync-plugin/blob/master/src/main/java/io/fabric8/jenkins/openshiftsync/BuildToActionMapper.java#L27 always returns an empty Map. And the only place it is called from is the BuildDecisionHandler. Shouldn't it also be populated during upsertBuild as that would be perfect time to update it based on new builds ?

**Comment by akram** [comment]
@waveywaves can we close this one?
It seems out-dated.
