### ISSUE TITLE
Feature request: support for Jenkins scheduled pipeline trigger

### ISSUE THREAD

**Issue by bendehaan** [openshift/jenkins-sync-plugin#336]
In similar fashion to the Jenkins scheduled pipeline, I would like to be able to automatically periodically trigger an OpenShift pipeline according to a cron(-like) specification.

The use case is for a security pipeline: long-running security jobs should not disrupt the regular build pipeline, and new security findings could arise in code that hasn't been touched for a while. A solution is to run the security pipeline periodically.

Note that we use ephemeral Jenkins, so configuring it there or through the Jenkinsfile wouldn't work.

The current workaround is to create an OpenShift 'cron job' that triggers the pipeline (oc start-build security-pipeline). However, doing this incurs the overhead of creating another image, while ideally it'd be configured in the regular buildconfig within the jenkinsPipelineStrategy.

If it's possible some other way, input is very welcome!

**Comment by andyfeller** [comment]
> The current workaround is to create an OpenShift 'cron job' that triggers the pipeline (oc start-build security-pipeline). However, doing this incurs the overhead of creating another image, while ideally it'd be configured in the regular buildconfig within the jenkinsPipelineStrategy.

@bendehaan : I agree it would be nice to configure a Jenkins job's build triggers via openshift-sync having just built something similar, however this is a little more difficult depending on whether you want to specify parameters and what happens in and around kicking off the build.

That being said, you don't have to build an image if all you need is to kick off a pre-existing `BuildConfig`; use an image like [openshift/origin-cli](https://hub.docker.com/r/openshift/origin-cli) and `CronJob` resource to `oc start-build`:
```
          containers:
            - name: "build-cron"
              image: "openshift/origin-cli:v3.11.0"
              imagePullPolicy: IfNotPresent
              command:
                - /bin/bash
                - -c
                - >-
                  echo "Starting build..."
                  && oc_res=$(oc start-build <BUILD-CONFIG> (-e PARAM=VALUE ...)
                  --wait)
                  && echo $oc_res
                  && build=$(echo $oc_res | grep -o -P '(?<=/).*(?= )')
                  && res=$(oc get build/$build | awk '{print $4}' | grep -v STATUS)
                  && echo $res
                  && if [ $res != "Complete" ]; then exit 1; fi
              resources:
                requests:
                  cpu: ...
                  memory: ...
                limits:
                  cpu: ...
                  memory: ...
```

You can start using this now until such time more official support is offered.

**Comment by akram** [comment]
@bendehaan as a more convenient exists for this case, I am closing the issue.
If you think that it may need better integration, let us know, so we can re-open it.

/close

**Comment by bendehaan** [comment]
@akram could you please enlighten me with regards to the more convenient solution or re-open this issue? The aforementioned solution is a workaround incurring additional (undesirable) complexity. If you have another solution, I would highly appreciate it if you could share it.
