### ISSUE TITLE
Secret name (credential Id) in Job is not reflected to BuildConfig

### ISSUE THREAD

**Issue by akram** [openshift/jenkins-sync-plugin#365]
- Create a build buil1
- Create a secret source secret1
- Create a secret source secret2
- Annotate them
- Link the secret source to the build1
- Run the build and check that it works
- Un Jenkins job clic Configure, change the Job secret from to secret1 to secret2

Result:
- oc edit bc build1
=> the sourceSecret is still secret1

```

oc new-build --code=git@github.com:akram/private-pipes.git#branch1 --name=build1

oc create secret generic my-private-ssh-key1 --from-file=ssh-privatekey=/Users/akram/.ssh/id_rsa.pub --from-literal=username=akram
oc create secret generic my-private-ssh-key2 --from-file=ssh-privatekey=/Users/akram/.ssh/id_rsa.pub --from-literal=username=akram

oc label secret my-private-ssh-key1  credential.sync.jenkins.openshift.io=true
oc label secret my-private-ssh-key2  credential.sync.jenkins.openshift.io=true


```

**Comment by waveywaves** [comment]
I was able to reproduce this, credentialsId is not being reflected in the BuildConfig.
