### ISSUE TITLE
Sync kubernetes.io/dockerconfigjson

### ISSUE THREAD

**Issue by savujevi** [openshift/jenkins-sync-plugin#371]
Hello developers,

is it possible to sync kubernetes.io/dockerconfigjson from OpenShift to Jenkins ?

Thank you for your help.

Best regards,
   Sascha Vujevic

**Comment by waveywaves** [comment]
@savujevi From what I understand you would like existing docker credentials to be synced via the syn plugin to be used by you Jenkins Pipeline. You should be able to sync this secret using this plugin. 
You would have to label the secret as done below to be picked up by the plugin.
`oc label secret test-secret credential.sync.jenkins.openshift.io=true`

**Comment by savujevi** [comment]
As mentioned in the doku:
"kubernetes.io/basic-auth" map to Jenkins Username / Password credentials
"kubernetes.io/ssh-auth" map to Jenkins SSH User credentials

kubernetes.io/dockerconfigjson is missing as I can see. I have tested it and the secret will not be synced.

Thank you for your help.

**Comment by nhomble** [comment]
/reopen

I'd be interested in this feature
