### ISSUE TITLE
Hanged Jobs

### ISSUE THREAD

**Issue by martincandal** [openshift/jenkins-sync-plugin#372]
Hi,
We are having problems with the openshift sync plugin (1.0.44) and CloudBees Core. Randomly, all buils start to queue on CloudBees and we have to restart the service to fix the problem. 
I talked to CloudBees Support and the told me that the problem is the OpenShift Sync plugin. I their analysis, they found a large number of threads in waiting and blocked state (199 and 4) and the blocked thread problem seems to be related to openshiftsync. It seems the openshiftsync tries to update a job but does not manage to do it.
Please check the attached screens and cloudbees logs.
Thanks
![TD_Summary](https://user-images.githubusercontent.com/54186364/73783960-5d478200-4773-11ea-89db-22a7d9347a76.png)
![OShift1](https://user-images.githubusercontent.com/54186364/73783961-5d478200-4773-11ea-922a-7076c493d1ce.png)
[jenkinshangWithJstack.126588.output.tar.gz](https://github.com/openshift/jenkins-sync-plugin/files/4155866/jenkinshangWithJstack.126588.output.tar.gz)
[cloudbees-support_core-cm-dev-master01.bancogalicia.com.ar_2020-02-03_18.51.13.zip](https://github.com/openshift/jenkins-sync-plugin/files/4155867/cloudbees-support_core-cm-dev-master01.bancogalicia.com.ar_2020-02-03_18.51.13.zip)

**Comment by andyfeller** [comment]
Can you confirm:
number of namespaces being synced
what turning on logging for the openshift-sync plugin shows the threads are doing?

**Comment by martincandal** [comment]
I have 35 namespaces. The attached logs came from the support bundle (i
think that is standard for jenkins and cloudbees) and the other log is
cbsupport, this is a tool from cloudbees support.

Thanks!
Martin

**Comment by andyfeller** [comment]
Can you confirm what rolebindings the Jenkins service account has been granted in the synced namespaces including the policy around `jenkins` resource?

**Comment by martincandal** [comment]
The jenkins account has the role edit in OpenShift.

Thanks!

**Comment by akram** [comment]
Hi @martincandal ,
Based on your logs, it seem that you have 32 namespaces configured for sync not 25.
Can you check that  the jenkins service account has sufficient permissions on all of these?

Did you face the issue with a previous version of the sync plugin?

**Comment by martincandal** [comment]
The SA has the edit role, I don’t know if is an standar role of openshift
or not. Can you describe the correct permissions?
Thanks!

**Comment by andyfeller** [comment]
OpenShift comes with [default `ClusterRole` resource types](https://docs.openshift.com/container-platform/3.11/architecture/additional_concepts/authorization.html#roles) with pre-determined policy sets for various resource types.  For openshift/jenkins to fully synchronize with a namespace including `Secret` resources that are intended to be Jenkins credentials, whether due to being source secrets in `BuildConfig` or labeled with `credential.sync.jenkins.openshift.io: true`, then the service account needs a rolebinding to a role capable of granting the permissions.  The easiest way outside of creating your own custom `ClusterRole` is to use the existing `edit` clusterrole.

So, with the 25 - 32 namespaces you have configured to by synced, each of those namespaces should have a `RoleBinding` granting the Jenkins service account from the namespace the service is running within enough privileges to view `BuildConfig`, `ConfigMap`, `Secret`, and `ImageStream` for synchronization.

Does that make sense?

**Comment by martincandal** [comment]
I was checking the errors in the log, for example, this one:
io.fabric8.kubernetes.client.KubernetesClientException: buildconfigs.build.openshift.io is forbidden: User "system:serviceaccount:default:sa-devops-cross" cannot watch buildconfigs.build.openshift.io in the namespace "fnpp-pagoproveedores-dev": no RBAC policy matched

I checked the fnpp-pagoproveedores-dev and the SA sa-devops-cross has the admin role. So I think the problem is not related to privileges. Also, the synchronization and build is working fine.
Thanks!

**Comment by andyfeller** [comment]
This error is the definition of a privilege issue:

> User "system:serviceaccount:default:sa-devops-cross" cannot watch buildconfigs.build.openshift.io in the namespace "fnpp-pagoproveedores-dev": no RBAC policy matched
>

**Comment by martincandal** [comment]
Look the role of the user: 
oc get rolebinding -n fnpp-pagoproveedores-dev
NAME                     ROLE                    USERS          GROUPS                                            SERVICE ACCOUNTS          SUBJECTS
admin                    /admin                  system:admin                                                     cicd/jenkins4
admin-0                  /admin                                                                                   cicd/jenkins
admin-1                  /admin                                                                                   cicd/jenkins1
admin-2                  /admin                                                                                   cicd/jenkins2
admin-3                  /admin                                                                                   cicd/jenkins3
admin-4                  /admin                                                                                   cicd/default
admin-5                  /admin                                                                                   cicd/jenkins5
admin-6                  /admin                                                                                   default/sa-devops-cross
admin-7                  /admin                                 system:serviceaccount:default:sa-devops-cross
edit                     /edit                                  GAPFNPPpagoproveedoresDEV
edit-0                   /edit                                  GAPOpenshiftDevOps
edit-1                   /edit                                  GAPFNPPpagoproveedoresVIEWER
edit-2                   /edit                                  GAPFNPPpagoproveedoresAPPROVER
limitrange-admin-cljwt   /limitrange-admin                      GAPOpenshiftDevOps
system:deployers         /system:deployer                                                                         deployer
system:image-builders    /system:image-builder                                                                    builder
system:image-pullers     /system:image-puller                   system:serviceaccounts:fnpp-pagoproveedores-dev

What should I check? beause for me, the privileges looks right.
Thanks!

**Comment by akram** [comment]
Assuming your jenkins instance is running in the namespace `default` and using the sa `system:serviceaccount:default:sa-devops-cross`  
you will have to run:

```
oc policy add-role-to-user edit system:serviceaccount:default:sa-devops-cross -n fnpp-pagoproveedores-dev
```
and then replace `fnpp-pagoproveedores-dev` and do it for each project.

**Comment by martincandal** [comment]
akram,
We are not running Jenkins inside OpenShift. We are running Cloudbees Core (Enterprise version of Jenkins) in a virtual server outside OpenShift.

**Comment by andyfeller** [comment]
@martincandal interesting.  so when this plugin is used on a Jenkins instance running within the cluster, it assumes the Kubernetes identity of the service account running.  I don’t know off the top of my head how the Kubernetes plugin is configured when the instance is external.  I’d have to check that out but any information you have on that would help troubleshoot this.

**Comment by martincandal** [comment]
Hi, any news about this?
