### ISSUE TITLE
Configuration with CASC Plugin fails when using openshift-sync-plugin and openshift-client-plugin

### ISSUE THREAD

**Issue by DonKodiyan** [openshift/jenkins-sync-plugin#394]
I'm using Jenkins with this image: quay.io/openshift/origin-jenkins:4.9.0
and using these plugins:
openshift-client:1.0.35
openshift-sync:1.0.48
configuration-as-code:1.51

When I try to configure jenkins using the CASC plugin, I'm getting this issue: 
2021-07-30 12:38:25 WARNING io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator handleDuplicateSymbols Found multiple implementations for symbol = openShiftToken: [io.fabric8.jenkins.openshiftsync.OpenShiftTokenCredentials$DescriptorImpl@6dcee025, com.openshift.jenkins.plugins.OpenShiftTokenCredentials$DescriptorImpl@314d64be]. Please report to plugin maintainer.  

This is my casc yaml configuration:
`credentials:
  system:
    domainCredentials:
    - credentials:
      - openShiftToken:
          id: "openshift"
          scope: GLOBAL
          secret: "<>"
`

**Comment by psimona** [comment]
This is a problem we are encountering too.

I suppose this has to do with the following classes:
- https://github.com/openshift/jenkins-sync-plugin/blob/master/src/main/java/io/fabric8/jenkins/openshiftsync/OpenShiftToken.java
- https://github.com/openshift/jenkins-sync-plugin/blob/master/src/main/java/io/fabric8/jenkins/openshiftsync/OpenShiftTokenCredentials.java

From your todo it seems you wanted to merge this with an other config class from the kubernetes plugin
```
// TODO: merge with https://github.com/jenkinsci/kubernetes-plugin/blob/master/src/main/java/org/csanchez/jenkins/plugins/kubernetes/OpenShiftTokenCredentialImpl.java 
```

Looking forward to a solution

**Comment by akram** [comment]
Hi @DonKodiyan ,

is that a regression? In a sense of: were you using OpenShift Sync plugin in an older version and then this bug appeared after upgrade?
Or you are a new user of the plugin?

The pointed code base has been unchanged for a while, but we have made several changes recently in other parts and components. So, wondering if it is a regression or an old issue.

**Comment by DonKodiyan** [comment]
Hi @akram 
I'm a new user of this image: https://github.com/openshift/jenkins
Since both plugins are already preinstalled ( https://github.com/openshift/jenkins/blob/b45f39eb8ff3bb2c0769cf9db4ce9bb0f64f31c1/2/contrib/openshift/base-plugins.txt#L29 ) the issue pops up immediately when using CASC Plugin with openShiftToken credentials.
