### ISSUE TITLE
allow the actual 'regular jenkins job definition XML' to be either stored inside the BuildConfig as an annotation, or for it to be a URL that points to where to get it from

### ISSUE THREAD

**Issue by jstrachan** [openshift/jenkins-sync-plugin#5]
so folks can store the build config in git somewhere, link to an existing jenkins job definition or embed it inside the BuildConfig (which is often stored in git via a source 'template YAML/JSON file' etc).

This is kinda low priority; am way more bothered about first class support for Pipeline jobs first and foremost - https://github.com/fabric8io/openshift-jenkins-sync-plugin/issues/4 - but its a way to help folks auto-create any old kind of Jenkins job via the XML config file

**Comment by gabemontero** [comment]
This notion (or something close enough to it) is being tracked via trello card https://trello.com/c/hPgz1K0X/1155-8-create-pipeline-buildconfigs-from-jenkins-jobs-pipelineintegration

Per our process closing out

@bparees fyi - of course correct me if I have mismatched these items

**Comment by bparees** [comment]
i'm not sure if this is quite the same or not.  it *probably* could be used to accomplish the same thing.

with the card proposal you'd create a job in jenkins(somehow, via any of the many mechanisms available) and then we'd create a BuildConfig in openshift for the job.

with what @jstrachan seems to want, you'd create a BuildConfig that contained a pointer to a jenkins job definition (or inlined the jenkins job definition), and the sync plugin would, as part of creating the job for the BuildConfig, use that jenkins job definition to configure the job.  Which would be a way to solve the "i need to fine tune the job that's created for my pipeline buildconfig" problem.

Again, both get you to the end goal of "i want to define complex jenkins jobs, but still have a corresponding buildconfig", but one approaches it from the BuildConfig side, and the other(the trello card) approaches it from the "define the job in jenkins" side (which would be aligned w/ use cases like using the github org plugin to create a bunch of jobs in jenkins and then have that also result in BuildConfigs)

**Comment by gabemontero** [comment]
On Wed, Jun 14, 2017 at 3:15 PM, Ben Parees <notifications@github.com>
wrote:

> i'm not sure if this is quite the same or not. it *probably* could be
> used to accomplish the same thing.
>
> with the card proposal you'd create a job in jenkins(somehow, via any of
> the many mechanisms available) and then we'd create a BuildConfig in
> openshift for the job.
>
> with what @jstrachan <https://github.com/jstrachan> seems to want, you'd
> create a BuildConfig that contained a pointer to a jenkins job definition
> (or inlined the jenkins job definition), and the sync plugin would, as part
> of creating the job for the BuildConfig, use that jenkins job definition to
> configure the job. Which would be a way to solve the "i need to fine tune
> the job that's created for my pipeline buildconfig" problem.
>
> Again, both get you to the end goal of "i want to define complex jenkins
> jobs, but still have a corresponding buildconfig", but one approaches it
> from the BuildConfig side, and the other(the trello card) approaches it
> from the "define the job in jenkins" side (which would be aligned w/ use
> cases like using the github org plugin to create a bunch of jobs in jenkins
> and then have that also result in BuildConfigs)
>

So I added a ref to this issue in the card we already have.  I can further
note that it *could* be a different option / approach, and we assess both
in tandem or one vs. the other as the card gets planned / scheduled.
Or would you rather have a separate card for this item?

**Comment by bparees** [comment]
I think they should be considered two separate items, but let's see if @jstrachan still wants this, in light of the other one, before we create a card for it.
