### ISSUE TITLE
Status is only synced for stages that have started

### ISSUE THREAD

**Issue by spadgett** [openshift/jenkins-sync-plugin#56]
This might be a limitation of the Jenkins pipeline plugin, but stages that haven't started aren't included in the JSON synced back to OpenShift. We'd like to build a UI that shows the user what stages are left. Is there any way to get a complete list of stages?

/cc @jimmidyson @bparees @fabianofranz

**Comment by ALRubinger** [comment]
/me Subscribed to notifications on the issue

**Comment by spadgett** [comment]
@smarterclayton FYI

**Comment by smarterclayton** [comment]
I chatted to jessica out this today, I was hoping we could improve what is put on the status so that we can hide the hard details from clients - i.e.:

1. When there is previous stage information, sketch it in as a "future stage"
2. Add any estimate / useful info to that previous stage info so we can provide "duration prediction"
3. If the new stage info doesn't match the predicted stage info, edit it out (or highlight it as removed)

That would let us do the predictive stuff in a way that is almost transparent to clients (and really boost the UI).  I expect stage changes to be rare.

**Comment by jimmidyson** [comment]
Any thoughts @jstrachan?

**Comment by ALRubinger** [comment]
A high-priority one for us now in visualizing the pipelines in the console; @jimmidyson, could you provide an update or point us to someone who might help us make some progress?  

I'll also be happy to work on it if someone can get me instructions to run/build/test it; I'm not seeing much in the way of docs or tests here in the repo; perhaps they're external somewhere?

**Comment by jstrachan** [comment]
@ALRubinger it might be worth asking the wider Jenkins community on how to query stages which have not yet been started. I've no idea if its even possible TBH

**Comment by jimmidyson** [comment]
I think the way it probably works is to query previous builds to build up the potential workflow for this build but someone needs to confirm that.

**Comment by ALRubinger** [comment]
+1.  Made a note to do just that.

**Comment by bparees** [comment]
@jstrachan @jimmidyson are we prepared to officially conclude it's not possible for the sync plugin to do this today, and start working upstream with cloudbees on how we can enable this capability?

I also have a related question:  when the buildconfig specifies a jenkinsfile that lives in git (not embedded in the buildconfig), how/when does the sync plugin obtain the Jenkinsfile from the git repo?  And how does it deal w/ private git repos that have credentials associated via api Secret objects, or proxy requirements defined in the buildconfig?

**Comment by gabemontero** [comment]
@bparees - don't know if you ever got an answer to your question last year re: how the sync plugin obtains the jenkinsfile that lives in git, but it is at https://github.com/openshift/jenkins-sync-plugin/blob/master/src/main/java/io/fabric8/jenkins/openshiftsync/BuildConfigToJobMapper.java#L55-L110

It happens on startup and whenever the watch receives an added/modified event.

**Comment by bparees** [comment]
@gabemontero thanks, since my comment was posted we did add support for private repos (as seen in that code) but it still does not respect any git proxy that the BC might define.  I believe we have an open issue or card for that.

**Comment by gabemontero** [comment]
wrt what is available, I can (re)confirm what I image @jimmidyson @ALRubinger @jstrachan determined last year ... it still appears that the only association of stages in the workflow plugin code is with the RunExt object, and those are as reported only the ones that have already executed.  There is no list of *all* the stages from the script file that are placed in the JobExt object or other object accessible to us.

Unless there are any direct contacts the fabric8 folks we should first cultivate, if we wanted to purse this, I would propose:

1) a post on the jenkins dev forum asking proposing the capability, asking if has been considered before or already under consideration, etc. .... see what discussion arises

2) unless that discussion steers us in a different direction, register the request at https://issues.jenkins-ci.org/browse/JENKINS-44470?jql=project%20%3D%20JENKINS%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20component%20%3D%20%27pipeline-stage-view-plugin%27

Before commencing, do we still want to pursue this?

thanks

**Comment by gabemontero** [comment]
On Fri, Jun 9, 2017 at 6:54 PM, Ben Parees <notifications@github.com> wrote:

> @gabemontero <https://github.com/gabemontero> thanks, since my comment
> was posted we did add support for private repos (as seen in that code) but
> it still does not respect any git proxy that the BC might define. I believe
> we have an open issue or card for that.
>
Yeah there are a few issues / bugzillas across the plugins wrt using
proxies ... in a couple of them there a references to open issues for
plugins like the git plugin as well having difficulty or odd reqs for using
proxies .... there is also a jenkins wiki that talks about which plugins
are "blessed" for supporting proxies, though it was a little unclean to me
on what they did to obtain such accreditation.  Definitely a bit of
investigation / research into this space could be required.

**Comment by bparees** [comment]
> Before commencing, do we still want to pursue this?

In my mind, the only way this could ever be supported is if something pre-parsed the jenkinsfile and attempted to extract the stages that will be executed, and that immediately becomes the halting problem given that jenkinsfiles are turing complete.  For anything other than trivial linear jenkinsfiles (which admittedly all our examples are), it's probably not possible to determine what the stages will be.

e.g.:
https://stackoverflow.com/questions/37690920/jenkins-pipeline-conditional-step-stage

So unless anyone disagrees w/ that assertion, I think we should close this as "not technically possible".

**Comment by gabemontero** [comment]
Haven't mined their code to see exactly how they do that, but I do see the `JobExt` class has the means to get prior runs.  We could create it from the `WorkflowJob` like we already create the `RunExt` instance today from the `WorkflowRun` class.  In theory multiple `RunExt` instances could have their refs decorated and serialized into JSON the same way a single instance is today.

How to annotate the build with the multiple json instances would be the next question.

Assuming educated guesses and approximate feature parity with the Jenkins UI are all sufficient / the goal here.

**Comment by bparees** [comment]
> From what I can tell from the Jenkins UI, it uses previous runs to make an educated guess about what the stages for the next run will be. If the previous run completed and ran these 5 stages, assume the next run will be the same until it diverges.

yes that's my impression too.  Doesn't our UI also do that?  If not, that seems like the logical thing to do (which doesn't require any changes to the sync plugin).

**Comment by gabemontero** [comment]
On Mon, Jun 12, 2017 at 12:10 PM, Ben Parees <notifications@github.com>
wrote:

> From what I can tell from the Jenkins UI, it uses previous runs to make an
> educated guess about what the stages for the next run will be. If the
> previous run completed and ran these 5 stages, assume the next run will be
> the same until it diverges.
>
> yes that's my impression too. Doesn't our UI also do that? If not, that
> seems like the logical thing to do (which doesn't require any changes to
> the sync plugin).
>
Sure, the question of "who" manages the history - the sync plugin or the
UI - is a legitimate one to ask / discuss.

**Comment by gabemontero** [comment]
Turns out, the recently introduced declarative pipeline syntax offers a way for to get the model of a successfully parsed pipeline.

With that, API are now available so that we can see learn what stages exist *BEFORE* they are executed.

It only works for the new declarative pipeline, not the original "scripted" pipeline.  "declarative" is strategic from the upstream jenkins perspective, so its use, which is already noticeable based on my interactions with users, should only be increasing.

@spadgett - where are the console team's priority today wrt augmenting the console's displaying of pipeline status vs. what they were in May 2016 when you opened this?

**Comment by spadgett** [comment]
@gabemontero I'd still say it's still a significant usability gap in our pipeline visualization compared to the Jenkins UI. If there is an API that could give us all stages for at least declarative pipelines, that would be extremely useful.

**Comment by gabemontero** [comment]
Roger that @spadgett 

I've opened https://trello.com/c/9cNMvbSj/1514-3-provide-pipeline-build-annotation-that-lists-declarative-pipeline-stages-even-before-they-are-executed-pipelineintegration

Per process, and with the take supporting the strategic, long term approach of declarative pipeline is sufficient, closing this issue out.
