### ISSUE TITLE
Development Docs

### ISSUE THREAD

**Issue by ALRubinger** [openshift/jenkins-sync-plugin#74]
Got the plugin built locally and running using `mvn hpi:run`.  Verified the plugin is installed at `http://localhost:8080/jenkins/pluginManager/installed`.  Next steps needed: how to interact with Jenkins/OpenShift together; what the expected flow is.  

I'll seed this issue with a PR for getting started w/ development as noted above, but will need some more detail about what next to get kicked off working on issues.

**Comment by bparees** [comment]
we've got openshift pipeline tutorials, i think this can be closed.

**Comment by bparees** [comment]
(doc in question: https://github.com/openshift/origin/tree/master/examples/jenkins/pipeline)

**Comment by bparees** [comment]
@jimmidyson ^^
