### ISSUE TITLE
can the sync plugin set the jenkins job number?

### ISSUE THREAD

**Issue by bparees** [openshift/jenkins-sync-plugin#92]
When the sync plugin is initially detecting the buildconfig definitions and creating the corresponding job definitions, would it be possible for that logic to also:
1) find all the builds associated with that buildconfig
2) look at the openshift.io/jenkins-build-url annotation to determine the highest job number that was ever associated with the buildconfig
3) set the job configuration in jenkins to start at that job number

that would allow us to restart jenkins without persistent storage while retaining consistent job urls.

@smarterclayton @spadgett @jimmidyson @jwforres

**Comment by tlalexan** [comment]
I'd be cautious about taking over the Jenkins build number, because Jenkins still offers much more functionality than openshift does in controlling the build label (e.g. can include version numbers and be calculated from the number of git commits since a tag).

**Comment by bparees** [comment]
At this point i think it's unlikely we're going to try to create a jenkins that's tolerant of ephemeral storage, there are way too many moving pieces we'd have to cover, so i'm closing this.
