### ISSUE TITLE
Support interactive user input ('input' steps)

### ISSUE THREAD

**Issue by fabianofranz** [openshift/jenkins-sync-plugin#94]
The Jenkins Pipeline plugin supports [steps that require interactive input from users](https://jenkins.io/doc/pipeline/steps/pipeline-input-step/), to allow for example something like "Approve? [yes button] [no button]". Interactive inputs are declared in the Jenkinsfile with the `input` step, for example

```
stage 'build'
input message: 'You REALLY want to build?', ok: 'Yes'
... proceed the build
```

When it reaches the `input` step, the build is **paused** and waits for user input. Jenkins provides a URL like `/job/sample-pipeline/ID/input/` where the user can manually approve the step in a screen similar to this:

![screenshot from 2016-07-08 20-07-57](https://cloud.githubusercontent.com/assets/158611/16703938/140be4fe-4548-11e6-8050-9b4d181d1f27.png)

So we need the Sync Plugin to sync back to the Build annotations 
1. something that allows us to know the build is waiting for user input (maybe a "waiting for input" status?), 
2. the URL "job/sample-pipeline/ID/input/" for manual approval.

With this we will be able to know in OpenShift that the given build is waiting for user input, display something about it, and link the URL pointing the user where to go to manually provide the information required and then continue the build.

**Comment by fabianofranz** [comment]
cc @jwforres @spadgett @ALRubinger

**Comment by fabianofranz** [comment]
Since for some reason I'm not seeing https://github.com/fabric8io/openshift-jenkins-sync-plugin/issues/85#issuecomment-231492176 anymore this morning, I just noticed we already have the `PAUSED_PENDING_INPUT` status which should fulfill 1. I should be able to guess 2 with `openshift.io/jenkins-build-uri` + the `/input/` suffix, but it would still be interesting to have it added to the information synced back to the build.

**Comment by spadgett** [comment]
I'm hesitant to assume anything about what the approval URL will be unless we're locking to a Jenkins version.

**Comment by sspeiche** [comment]
What when 1 user uses OpenShift UI to approve but a millisecond later, someone else uses Jenkins Web UI or API to abort. The sync plugin will see the change on OpenShift side and try to "yeah totes" it or will it see the "abort" status on the Jenkins side? What feedback will the OpenShift users get? Will it just changed to "abort"

**Comment by jwforres** [comment]
It isn't using our UI to approve, the approval link goes to the approval
page in Jenkins.

**Comment by gabemontero** [comment]
PR https://github.com/openshift/jenkins-sync-plugin/pull/137 is adding the annotation for 2)

when it merges (and it should after 3.6 code freeze), I am going to close this issue out

@sspeiche - to add to @jwforres 's clarification, the race condition you noted exists with OpenShift UI out of the picture and 2 users from the Jenkins Web UI doing "simultaneous" abort / approve ... I see no coordination/locking on the Jenkins side ... going to punt on it from a sync plugin perspective

**Comment by gabemontero** [comment]
Update - PR https://github.com/openshift/jenkins-sync-plugin/pull/137 has merged with its annotation for 2).

We are not including that change in 3.7, so I will not cut a version of the plugin / update the jenkins centos image with this until after 3.7 is out the door, and will hence still leave this open for now.

But I'll close this out when those two items in fact occur and y'all have something to try out.

**Comment by gabemontero** [comment]
I should be able to craft the new version of sync pluging (think I'm going to call it 1.0) sometime this week with the new prompt annotation.

As a preview using the openshift bluegreen example template, the json in the annotation will look like:

```
[{"id":"Approval","proceedText":"Proceed","message":"Test deployment: http://green-nodejs-mongodb-example-myproject.127.0.0.1.nip.io. Approve?","inputs":[],"proceedUrl":"//job/myproject/job/myproject-bluegreen-pipeline/1/wfapi/inputSubmit?inputId=Approval","abortUrl":"//job/myproject/job/myproject-bluegreen-pipeline/1/input/Approval/abort","redirectApprovalUrl":"//job/myproject/job/myproject-bluegreen-pipeline/1/input/"}]
```

**Comment by gabemontero** [comment]
the oenshift jenkins centos image on docker hub now as the sync plugin change that supports what I've documented above

closing out 

enjoy :-)
